import { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Header } from './Header'
import { Footer } from './Footer'


export default function Home() {



    useEffect(() => {
        require("bootstrap/dist/js/bootstrap");
    }, [])


    return (
        <div className='main-container container-fluid p-0'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="@next/font/google/Lato" rel="steelsheet" />
                <link href="@next/font/google/Montserrat" rel="steelsheet" />
            </Head>
            <div className="container-fluid p-0">
                <Header />
            </div>
            <div className="hero-container container mt-5 mb-5">
                <div className="row">
                    <div className="col-lg-6 col-sm-12">
                        <h1 className="hero-title mb-5">Trans-garona,</h1>
                        <div className="row hero-container-content ps-lg-5">
                            <h2 className="hero-subtitle mb-3">
                                une piste cyclable transfrontalière aux abords de la Garonne… qui coule de source
                            </h2>
                            <p className="hero-top-content mb-3">
                                Un projet de coopération qui concrétise une ambition partagée par le Département de la Haute-Garonne et le Conselh Generau d’Aran
                            </p>
                            <p className="hero-bottom-content">
                                Le projet TRANS-GARONA est né de la volonté conjointe du Département de la Haute-Garonne et du Conseil Général d’Aran de développer
                                les mobilités douces et le cyclotourisme aux abords de la Garonne, ce patrimoine commun, depuis sa source jusqu’à son estuaire grâce à la connexion avec l'
                                <span className="hero-bottom-content-span">
                                    itinéraire cyclable du Canal des Deux Mers (V80) à Toulouse.
                                </span>
                            </p>
                        </div>
                    </div>
                    <div className="col-6 d-none d-lg-block mt-2">
                        <Image
                            alt="hero-picture"
                            src="/assets/images/hero-picture.png"
                            width="435"
                            height="580"
                        />
                    </div>
                </div>
            </div>
            <div className="container quote-container mt-5">
                <div className="row">
                    <div className='col-lg-8 col-md-12'>
                        <p className='top-quote-container ps-lg-5'>
                            La réalisation de la piste cyclable Trans-Garona concrétise un bel exemple de coopération
                            transfrontalière entre le Conseil départemental de la Haute-Garonne et le Conselh Generau d’Aran.
                        </p>
                        <p className='bottom-quote-container ps-lg-5'>
                            Au cœur du massif pyrénéen, les richesses de nos territoires sont multiples et les liens
                            qui nous unissent historiques. Ce potentiel, nous avons souhaité le valoriser en matière
                            d’aménagement du territoire, de développement touristique et économique, d’offre de loisirs sportifs et culturels,
                            de protection de l’environnement et de la biodiversité.
                        </p>
                    </div>
                    <div className="quote-card-container col-lg-4 col-md-12 d-flex flex-md-row flex-lg-column">
                        <div className="row quote-card">
                            <div className="quote-card-picture col-md-4">
                                <Image src="/assets/images/GeorgeMeric.png" alt="GeorgeMeric-picture" height="64" width="64" />
                            </div>
                            <div className="quote-card-content col-md-8">
                                <p className="quote-card-title">
                                    George Meric
                                </p>
                                <p className="quote-card-subtitle">
                                    Président du Conseil Départemental
                                </p>
                            </div>
                        </div>
                        <div className="row quote-card">
                            <div className="quote-card-picture col-md-4">
                                <Image src="/assets/images/MariaVerges.png" alt="MariaVerges-picture" height="64" width="64" />
                            </div>
                            <div className="quote-card-content col-md-8">
                                <p className="quote-card-title">
                                    Maria Verges
                                </p>
                                <p className="quote-card-subtitle">
                                    Sindica d'Aran
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="container ">
                <div className="row">
                    <div className="col-md-10 p-5 temoignage-top-container">
                        <h2>
                            Un projet soutenu financièrement par l’Union Européenne à travers le programme européen de coopération
                            transfrontalière POCTEFA 2014-2020 source
                        </h2>
                    </div>
                </div>
            </div>
            <div className="container picture-container p-5">
                <div className="row">
                    <div className="col-sm-12 d-flex justify-content-center mb-5">
                        <Image className="img-fluid" src="/assets/images/Image.png" alt="image-plante" height="407" width="720" />
                    </div>
                </div>
                <div className="row mb-5">
                    <div className="col-6 d-flex justify-content-center maconnery-container">
                        <Image className="img-fluid maconnery-picture pe-2" src="/assets/images/logo-hautegaronne.png" alt="logo-haute-garonne" height="192" width="341" />
                    </div>
                    <div className="col-6 d-flex justify-content-center maconnery-container">
                        <Image className="img-fluid maconnery-picture ps-3" src="/assets/images/logo-conselh.png" alt="logo-conselh" height="192" width="341" />
                    </div>
                </div>
                <div className="row">
                    <div className="col-6 d-flex justify-content-center maconnery-container">
                        <Image className="img-fluid maconnery-picture" src="/assets/images/logo-hautegaronne.png" alt="logo-haute-garonne" height="192" width="341" />
                    </div>
                    <div className="col-6 d-flex justify-content-center maconnery-container">
                        <Image className="img-fluid maconnery-picture ps-3" src="/assets/images/logo-conselh.png" alt="logo-conselh" height="192" width="341" />
                    </div>
                </div>
            </div>
            <Footer />


            {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
        </div>
    )
}
